# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OffOff_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OffOff_iOS
  # MDC TextField
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/TextControls+OutlinedTextAreas'
  pod 'MaterialComponents/TextControls+OutlinedTextFields'
  
  #MDC Button
  pod 'MaterialComponents/Buttons'

  target 'OffOff_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
